### ISSUE TITLE
If `spec/support` directory does not exist, deprecation tracking fails with an ENOENT

### ISSUE THREAD

**Issue by etagwerker** [fastruby/next_rails#13]
Here are the steps to reproduce this issue: 

1. Use a Rails application that has RSpec set up. 
2. Make sure that `spec/support` does not exist. If it exists, remove that directory.
3. Run your test suite with `DEPRECATION_TRACKER=save` in order to save all deprecation warnings in a JSON file.

## Current behavior 

It will raise an Errno::ENOENT error because it can't find that directory (`spec/support`)

## Expected behavior 

It should create the directory if it doesn't find it. It should not raise an Errno::ENOENT

## Notes

Here is the output that I have where I was trying to save deprecation warnings: 

```
DEPRECATION_TRACKER=save bundle exec rspec

Randomized with seed 51288
.............................................Capybara starting Puma...
* Version 3.12.6 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:55653
.Unexpected confirm modal - accepting.You should be using `accept_confirm` or `dismiss_confirm`.
.......................................
An error occurred in an `after(:suite)` hook.
Failure/Error:
  File.open(dest, 'wb', s.stat.mode) do |f|
    IO.copy_stream(s, f)
  end

Errno::ENOENT:
  No such file or directory @ rb_sysopen - spec/support/deprecation_warning.shitlist.json
# /Users/etagwerker/.rvm/gems/ruby-2.5.7/gems/next_rails-1.0.2/lib/deprecation_tracker.rb:133:in `save'
# /Users/etagwerker/.rvm/gems/ruby-2.5.7/gems/next_rails-1.0.2/lib/deprecation_tracker.rb:64:in `block in track_rspec'


Finished in 14.14 seconds (files took 4.19 seconds to load)
85 examples, 0 failures, 1 error occurred outside of examples

Randomized with seed 51288
```

The project that I was using is https://github.com/fastruby/points which is open source too.

**Comment by etagwerker** [comment]
This was fixed and shipped in v1.0.5 thanks to @rishijain! ❤️
